### ISSUE TITLE
enum support in arch_config.yaml not working...

### ISSUE THREAD

**Issue by salmanap** [katanemo/archgw#212]
If you add an enum to arch_config the validation fails on archgw up.
```
       parameters:
        - name: staffing_type
          type: str
          description: Staffing type like contract, fte or agency
          required: true
          enum: [fte, contract, agency]
        - name: region
          type: str
          required: true
          description: Geographical region for which you want workforce data like asia, europe, americas.
 ```
