### ISSUE TITLE
Groq: LLama-based completions not supported in llm_gateway

### ISSUE THREAD

**Issue by Spherrrical** [katanemo/archgw#458]
When attempting to use Groq's LLama models with Arch, the system incorrectly processes the response format. The llm_gateway appears to recognize the provider and model (provider: Groq, model selected: llama-3.2-3b-preview), but it's not properly handling the response format from Groq's API.

We get an error `non chat-completion compliant response received err: missing field 'choices' at line 8 column 1`

The `api_key` works sufficiently as tested locally with a cURL command:
```
➜  ~ curl https://api.groq.com/openai/v1/chat/completions \
  -H "Authorization: Bearer gsk_******" \
  -H "Content-Type: application/json" \
  -d '{
    "model": "llama-3.2-3b-preview",
    "messages": [{"role": "user", "content": "Hello"}],
    "max_tokens": 10
  }'
{"id":"chatcmpl-2db8b749-d52e-4c49-8e27-2615ab88c525","object":"chat.completion","created":1744326584,"model":"llama-3.2-3b-preview","choices":[{"index":0,"message":{"role":"assistant","content":"Hello. How can I assist you today?"},"logprobs":null,"finish_reason":"length"}],"usage":{"queue_time":0.01967895,"prompt_tokens":36,"prompt_time":0.006995408,"completion_tokens":10,"completion_time":0.006487843,"total_tokens":46,"total_time":0.013483251},"usage_breakdown":{"models":null},"system_fingerprint":"fp_a926bfdce1","x_groq":{"id":"req_01jrgzesnwf9jb2wr8ybqjwv5e"}}
```
### Environment
Docker Desktop
Valid API Key
archgw 0.2.5

### YAML Configuration:

```yaml
version: v0.1

listeners:
  ingress_traffic:
    address: 0.0.0.0
    port: 10000
    message_format: openai
    timeout: 10s

endpoints:
  ai_service:
    endpoint: agent.clubcentric.org
    protocol: https

llm_providers:
  - name: Groq
    provider_interface: openai
    access_key: $GROQ_AGENT_API_KEY
    model: llama-3.2-3b-preview
    default: true

overrides:
  prompt_target_intent_matching_threshold: 0.65
  optimize_context_window: true

  
prompt_guards:
  input_guards:
    jailbreak:
      on_exception:
        message: Looks like you're curious about my abilities, but I can only provide assistance with ClubCentric and clubs. Is there something else I can help you with?

system_prompt: |
  You are the ClubCentric AI assistant, named "Club Agent". You help users generate forms and meeting agendas for their clubs. Make sure you use the correct endpoint for the request. If it's meeting agendas, use the /ai/v1/meetings/generate endpoint. If it's form generation, use the /ai/v1/forms/generate endpoint.
  
  For form generation, collect information about the club (ID, name) and the purpose of the form.
  For meeting agendas, collect information about the club, meeting type, and purpose.
  
  Respond in a helpful and friendly manner, focusing on delivering the requested content.

prompt_targets:
  - name: generate_form
    description: Generate a form for a club based on provided information
    endpoint:
      name: ai_service
      path: /ai/v1/forms/generate
      http_method: POST
      http_headers:
        Authorization: "Bearer $SUPABASE_TOKEN"
    parameters:
      - name: club_id
        type: str
        description: The club ID
        required: true
      - name: club_name
        type: str
        description: The name of the club
        required: true
      - name: purpose
        type: str
        description: The purpose of the form
        required: true
    auto_llm_dispatch_on_response: true

  - name: generate_meeting
    description: Generate a meeting agenda for a club
    endpoint:
      name: ai_service
      path: /ai/v1/meetings/generate
      http_method: POST
      http_headers:
        Authorization: "Bearer $SUPABASE_TOKEN"
    parameters:
      - name: club_name
        type: str
        description: The name of the club
        required: true
      - name: meeting_type
        type: str
        description: The type of meeting (e.g., General, Board, Planning)
        required: true
      - name: purpose
        type: str
        description: The purpose of the meeting
        required: true
    auto_llm_dispatch_on_response: true

  - name: health_check
    description: Check if the AI service is operational
    endpoint:
      name: ai_service
      path: /health
      http_method: GET
    auto_llm_dispatch_on_response: false
```

Attached is a log of the Docker logs.

[arch-logs.txt](https://github.com/user-attachments/files/19695431/arch-logs.txt)

Thanks for your help, amazing tool :)
