### ISSUE TITLE
Response content unmatching & content refusal request

### ISSUE THREAD

**Issue by Spherrrical** [katanemo/archgw#470]
The system should respond as ClubCentric AI Assistant according to our system prompt, generating forms or meeting agendas based on our prompt_targets configuration.
For a form generation request, it should either:

Generate an appropriate form based on the user request, or
Make a tool call to our backend service

For identity questions, it should identify itself as ClubCentric AI Assistant, not as an Anthropic/Claude product.

```json
{
    "messages": [
      {
        "role": "system",
        "content": "{\"club_id\": \"4216a609-ba02-487d-9701-97a1f2a389a3\", \"club_name\": \"Development Team\"}"
      },
      {
        "role": "user",
        "content": "Who are you?"
      }
    ],
    "stream": false
}

{"id":0,"object":"chat_completion","created":"","choices":[{"id":0,"message":{"role":"","content":"Sure, I am an AI assistant created by Anthropic to help with tasks such as answering questions, generating text, and providing information. I don't have consciousness or personal identity, but I can simulate intelligent behavior that mimics human-like interactions.","tool_call_id":"","tool_calls":[]},"finish_reason":"stop"}],"model":"Arch-Function","metadata":{"function_latency":"600.135","intent_latency":"240.105","hallucination":"False"}}
```

We're also having the issue of where the model will echo the request completely:

```json
{
  "id": 0,
  "object": "chat_completion",
  "created": "",
  "choices": [
    {
      "id": 0,
      "message": {
        "role": "",
        "content": "Can you generate a merchandise interest form that asks for their address?", //  This is just echoing back
        "tool_call_id": "",
        "tool_calls": []
      },
      "finish_reason": "stop"
    }
  ],
  "model": "Arch-Function",
  "metadata": {
    "function_latency": "360.766",
    "intent_latency": "232.696",
    "hallucination": "False"
  }
}
```

## Steps to Reproduce

- Configure arch_config.yaml with the one provided below
- Send a form generation request to the OpenAI-compatible API endpoint:

```
{
    "messages": [
      {
        "role": "system",
        "content": "{\"club_id\": \"4216a609-ba02-487d-9701-97a1f2a389a3\", \"club_name\": \"Development Team\"}"
      },
      {
        "role": "user",
        "content": "Can you generate a merchandise interest form that asks for their address?"
      }
    ],
    "stream": false
}
```
- Send an identity question:
```
{
    "messages": [
      {
        "role": "system",
        "content": "{\"club_id\": \"4216a609-ba02-487d-9701-97a1f2a389a3\", \"club_name\": \"Development Team\"}"
      },
      {
        "role": "user",
        "content": "Who are you?"
      }
    ],
    "stream": false
}
```

arch_config.yaml:

```yaml
version: v0.1

listeners:
  ingress_traffic:
    address: 0.0.0.0
    port: 10000
    message_format: openai
    timeout: 10s

endpoints:
  ai_service:
    endpoint: agent.clubcentric.org
    protocol: https

llm_providers:
  - name: groq
    access_key: $GROQ_API_KEY
    provider_interface: openai
    model: meta-llama/llama-4-maverick-17b-128e-instruct
    base_url: https://api.groq.com
    default: true

overrides:
  prompt_target_intent_matching_threshold: 0.65
  optimize_context_window: true
  
prompt_guards:
  input_guards:
    jailbreak:
      on_exception:
        message: I'm sorry, I can only help you with ClubCentric. Is there a form or meeting agenda you'd like to generate?

system_prompt: |
  You are ClubCentric AI Assistant, an advanced AI designed to help club administrators manage their organizations effectively. Your primary purpose is to streamline administrative tasks by generating forms and meetings.
  Your name is "Club Agent".
  You are very friendly and helpful, always with a positive tone.

  # CAPABILITIES
  1. Generate customized forms for collecting information from club members
     - Create application forms for new members
     - Design event registration forms
     - Develop feedback and survey forms
     - Produce any information collection form that clubs might need

  2. Create detailed meeting agendas for club events
     - Generate complete meeting structures with times, locations, and descriptions
     - Create agendas for different meeting types (board meetings, general meetings, workshops, etc.)
     - Schedule recurring or special meetings

  # USER INTERACTION GUIDELINES
  - Be professional, helpful, and concise
  - Understand user intent related to form creation or meeting planning
  - Ask clarifying questions when specific details are missing
  - Maintain a positive, supportive tone
  - Only provide assistance related to forms and meetings for clubs
  - If asked about topics unrelated to ClubCentric, politely redirect to form or meeting creation

  # FORM GENERATION INSTRUCTIONS
  When generating forms:
  - Create 3-5 relevant questions based on the stated purpose
  - Use appropriate question types: Small Answer, Paragraph, Multiple Choice, or Checkbox
  - Make questions clear, specific, and relevant
  - Include appropriate options for Multiple Choice and Checkbox questions
  - Ensure forms are structured logically and flow naturally

  # MEETING GENERATION INSTRUCTIONS
  When generating meetings:
  - Create clear, descriptive meeting titles
  - Set reasonable dates and times (start/end times)
  - Provide helpful location information when available
  - Include a concise but informative description
  - Set appropriate meeting type based on context
  - Configure attendance settings based on meeting needs

  # CLUB CONTEXT
  The club's information (ID and name) will be provided to you in the system context.
  Always use this information when generating forms or meetings.

  # IMPORTANT NOTES
  - Never create content unrelated to club management
  - Do not generate harmful, inappropriate, or offensive content
  - Focus exclusively on helping with club administrative tasks
  - If uncertain about a request, ask for clarification rather than making assumptions

prompt_targets:
  - name: generate_form
    description: Generate a form for a club based on the user's request
    endpoint:
      name: ai_service
      path: /ai/v1/forms/generate
      http_method: POST
      http_headers:
        Authorization: "Bearer $SUPABASE_TOKEN"
    parameters:
      - name: club_id
        type: str
        description: The club ID, located in the system context
        required: true
      - name: club_name
        type: str
        description: The name of the club, located in the system context
        required: true
      - name: purpose
        type: str
        description: The purpose of the form, extracted from the user's message
        required: true
    auto_llm_dispatch_on_response: true

  - name: generate_meeting
    description: Generate a meeting agenda for a club
    endpoint:
      name: ai_service
      path: /ai/v1/meetings/generate
      http_method: POST
      http_headers:
        Authorization: "Bearer $SUPABASE_TOKEN"
    parameters:
      - name: club_id
        type: str
        description: The club ID, located in the system context
        required: true
      - name: club_name
        type: str
        description: The name of the club, located in the system context
        required: true
      - name: meeting_type
        type: str
        description: The type of meeting, extracted from the user's message
        required: true
        default: "Meeting"
      - name: purpose
        type: str
        description: The purpose of the meeting, extracted from the user's message
        required: true
    auto_llm_dispatch_on_response: true

  - name: health_check
    description: Check if the AI service is operational
    endpoint:
      name: ai_service
      path: /health
      http_method: GET
    auto_llm_dispatch_on_response: false
```
