### ISSUE TITLE
Parse problems on ollama metrics

### ISSUE THREAD

**Issue by codefromthecrypt** [katanemo/archgw#504]
If you run archgw against a config like this, where the model is ollama, so has a dot in it:

```
version: "0.1-beta"

listeners:
  egress_traffic:
    address: 0.0.0.0
    port: 12000
    message_format: openai
    timeout: 30s

llm_providers:
  - name: qwen3:0.6b
    provider_interface: openai
    # This configuration is converted to Envoy and run inside Docker.
    endpoint: host.docker.internal:11434
    model: qwen3:0.6b
    default: true

tracing:
  random_sampling: 100
  trace_arch_internal: true
```

Then, you look at the metrics endpoint here:

http://localhost:19901/stats?format=prometheus

You'll see improper truncation of the model like this:
```
# TYPE envoy_cluster_6b_assignment_stale counter
envoy_cluster_6b_assignment_stale{envoy_cluster_name="qwen3_0"} 0
```

What do you recommend to fix this?
