### ISSUE TITLE
Update config to keep all elements at top level

### ISSUE THREAD

**Issue by adilhafeez** [katanemo/archgw#7]
Right now our config looks like this,

```yaml
katanemo-prompt-config:
  default-prompt-endpoint: "127.0.0.1"
  load-balancing: "round-robin"
  timeout-ms: 5000

  embedding-provider:
    ...

  llm-providers:
      ...

  system-prompt: |
    ...

  prompt-targets:
    ...
```

But more idiomatic way to define yaml config is to place elements at top level (i.e. remove `katanemo-prompt-config`). After update config should see config look like this,

```yaml
default-prompt-endpoint: "127.0.0.1"
load-balancing: "round-robin"
timeout-ms: 5000

embedding-provider:
  ...

llm-providers:
    ...

system-prompt: |
  ...

prompt-targets:
  ...
```
